class Keys():
    LeftMouseDown = 'left mouse down'
    LeftMouseUp = 'left mouse up'
    MiddleMouseDown = 'middle mouse down'
    MiddleMouseUp = 'middle mouse up'
    RightMouseDown = 'right mouse down'
    RightMouseUp = 'right mouse up'
    DoubleClick = 'double click'
    ScrollUp = 'scroll up'
    ScrollDown = 'scroll down'
    LeftArrow = 'left arrow'
    LeftArrowUp = 'left arrow up'
    UpArrow = 'up arrow'
    UpArrowUp = 'up arrow up'
    DownArrow = 'down arrow'
    DownArrowUp = 'down arrow up'
    RightArrow = 'right arrow'
    RightArrowUp = 'right arrow up'
    LeftControl = 'left control'
    RightControl = 'right control'
    LeftShift = 'left shift'
    RightShift = 'right shift'
    LeftAlt = 'left alt'
    RightAlt = 'right alt'
    LeftControlUp = 'left control up'
    RightControlUp = 'right control up'
    LeftShiftUp = 'left shift up'
    RightShiftUp = 'right shift up'
    LeftAltUp = 'left alt up'
    RightAltUp = 'right alt up'
    PageDown = 'page down'
    PageDownUp = 'page down up'
    PageUp = 'page up'
    PageUpUp = 'page up up'
    Enter = 'enter'
    Backspace = 'backspace'
    Escape = 'escape'
    Tab = 'tab'
    Space = 'space'
    GamepadLeftStickX = 'gamepad left stick x'   
    GamepadLeftStickY = 'gamepad left stick y'   
    GamepadRightStickX = 'gamepad right stick x'   
    GamepadRightStickY = 'gamepad right stick y'   
    GamepadLeftTrigger = 'gamepad left trigger'   
    GamepadRightTrigger = 'gamepad right trigger'
    GamepadA = 'gamepad a'
    GamepadAUp = 'gamepad a up'
    GamepadB = 'gamepad b'
    GamepadBUp = 'gamepad b up'
    GamepadX = 'gamepad x'
    GamepadXUp = 'gamepad x up'
    GamepadY = 'gamepad y'
    GamepadYUp = 'gamepad y up'
    GamepadLeftStick = 'gamepad left stick'
    GamepadLeftStickUp = 'gamepad left stick up'
    GamepadRightStick = 'gamepad right stick'
    GamepadRightStickUp = 'gamepad right stick up'
    GamepadBack = 'gamepad back'
    GamepadBackUp = 'gamepad back up'
    GamepadStart = 'gamepad start'
    GamepadDpadDown = 'gamepad dpad down'
    GamepadDpadDownUp = 'gamepad dpad down up'
    GamepadDpadUp = 'gamepad dpad up'
    GamepadDpadUpUp = 'gamepad dpad up up'
    GamepadDpadLeft = 'gamepad dpad left'
    GamepadDpadLeftUp = 'gamepad dpad left up'
    GamepadDpadRight = 'gamepad dpad right'
    GamepadDpadRightUp = 'gamepad dpad right up'
    GamepadLeftShoulder = 'gamepad left shoulder'
    GamepadLeftShoulderUp = 'gamepad left shoulder up'
    GamepadRightShoulder = 'gamepad right shoulder'
    GamepadRightShoulderUp = 'gamepad right shoulder up'
    PrefixControl = 'control-'
    PrefixShift = 'shift-'
    PrefixAlt = 'alt-'
    A = 'a'
    B = 'b'
    C = 'c'
    D = 'd'
    E = 'e'
    F = 'f'
    G = 'g'
    H = 'h'
    I = 'i'
    J = 'j'
    K = 'k'
    L = 'l'
    M = 'm'
    N = 'n'
    O = 'o'
    P = 'p'
    Q = 'q'
    R = 'r'
    S = 's'
    T = 't'
    U = 'u'
    V = 'v'
    W = 'w'
    X = 'x'
    Y = 'y'
    Z = 'z'
    NumberOne = "1"
    NumberTwo = "2"
    SemiColon = ";"
    InputNameChanges = {
        'mouse1' : 'left mouse down', 'mouse1 up' : 'left mouse up', 'mouse2' : 'middle mouse down', 'mouse2 up' : 'middle mouse up', 'mouse3' : 'right mouse down', 'mouse3 up' : 'right mouse up',
        'wheel_up' : 'scroll up', 'wheel_down' : 'scroll down',
        'arrow_left' : 'left arrow', 'arrow_left up' : 'left arrow up', 'arrow_up' : 'up arrow', 'arrow_up up' : 'up arrow up', 'arrow_down' : 'down arrow', 'arrow_down up' : 'down arrow up', 'arrow_right' : 'right arrow', 'arrow_right up' : 'right arrow up',
        'lcontrol' : 'left control', 'rcontrol' : 'right control', 'lshift' : 'left shift', 'rshift' : 'right shift', 'lalt' : 'left alt', 'ralt' : 'right alt',
        'lcontrol up' : 'left control up', 'rcontrol up' : 'right control up', 'lshift up' : 'left shift up', 'rshift up' : 'right shift up', 'lalt up' : 'left alt up', 'ralt up' : 'right alt up',
        'control-mouse1' : 'left mouse down', 'control-mouse2' : 'middle mouse down', 'control-mouse3' : 'right mouse down',
        'shift-mouse1' : 'left mouse down', 'shift-mouse2' : 'middle mouse down', 'shift-mouse3' : 'right mouse down',
        'alt-mouse1' : 'left mouse down', 'alt-mouse2' : 'middle mouse down', 'alt-mouse3' : 'right mouse down',
        'page_down' : 'page down', 'page_down up' : 'page down up', 'page_up' : 'page up', 'page_up up' : 'page up up',
    }
    SpecialWhiteListKeys = {
        'mouse1' : LeftMouseDown,
        'mouse1 up' : LeftMouseUp, 
        'mouse2' : MiddleMouseDown, 
        'mouse2 up' : MiddleMouseUp, 
        'mouse3' : RightMouseDown, 
        'mouse3 up' : RightMouseUp
    }